config/routes.rb
RailsApp::Application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, :path => "/", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification'}#, :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  get "front/index"
  get "front/admin", :as=>"front_admin"

  resources :categories, only: [:show]

  resources :articles, only: [:show, :index]

  namespace 'admin' do
    resources :articles
    resources :categories
  end  

  root :to=>"front#index", :as=>"front"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :category_id, :published, :published_at, :title, :user_id
  belongs_to :category

  default_scope :order => 'published_at DESC'
  scope :recent, where(:published => true).limit(20)

  validates_presence_of :title
  validates_presence_of :body
  validates_length_of :title, :maximum => 255
  validates_length_of :body, :maximum => 20000

  before_save :update_published_at#, :random_file_name

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
                    :default_url => "/images/:style/missing.png", :whiny => false,
                    :url => "/uploadfiles/:class/:attachment/:id_partition/:basename_:style.:extension",
                    :path => ":rails_root/public/uploadfiles/:class/:attachment/:id_partition/:basename_:style.:extension"

  private
	  def update_published_at
	  	self.published_at = Time.now if published == true
	  end

    def random_file_name
      if File.extname(avatar_file_name).present?
        extension = File.extname(avatar_file_name).downcase
        self.avatar.instance_write(:file_name, "#{Time.now.strftime("%Y%m%d%H%M%S")}#{rand(1000)}#{extension}")
      end
    end
end

app/controllers/admin/articles_controller.rb
# encoding: utf-8
class Admin::ArticlesController < Admin::BaseController  
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate :page=>params[:page], :per_page => 20

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: '成功创建文章.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: '成功更新文章.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to admin_articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :update, :destory]
  # GET /articles
  # GET /articles.json
  # def index
  #   @articles = Article.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @articles }
  #   end
  # end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # # GET /articles/new
  # # GET /articles/new.json
  # def new
  #   @article = Article.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @article }
  #   end
  # end

  # # GET /articles/1/edit
  # def edit
  #   @article = Article.find(params[:id])
  # end

  # # POST /articles
  # # POST /articles.json
  # def create
  #   @article = Article.new(params[:article])

  #   respond_to do |format|
  #     if @article.save
  #       format.html { redirect_to @article, notice: 'Article was successfully created.' }
  #       format.json { render json: @article, status: :created, location: @article }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PUT /articles/1
  # # PUT /articles/1.json
  # def update
  #   @article = Article.find(params[:id])

  #   respond_to do |format|
  #     if @article.update_attributes(params[:article])
  #       format.html { redirect_to @article, notice: 'Article was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @article.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /articles/1
  # # DELETE /articles/1.json
  # def destroy
  #   @article = Article.find(params[:id])
  #   @article.destroy

  #   respond_to do |format|
  #     format.html { redirect_to articles_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= simple_form_for( [:admin, @article], :html => { :class => 'span8 form-horizontal well'  }) do |f| %>
  <%= f.input :title, label: "标题" || t('.article_title')  %><br />
  <%= f.cktext_area :body, label: "内容" || t('.article_content') %><br />
  <%= f.association :category, label: "分类" || t('.article_category'), include_blank: false%>  
  <%= f.input :published, label: "发布" || t('.published') %>
  <%= f.submit "保存" || t('.save'), :class => "btn btn-primary" %>
  <%= link_to '取消', admin_articles_path, :class => "btn btn-info" %>
<% end %>

app/views/admin/articles/edit.html.erb
<h1><%= '编辑文章'||t('.edit_article_head') %></h1>

<%= render 'form' %>

<% link_to 'Show', @article %>
<% link_to 'Back', admin_articles_path %>

app/views/admin/articles/index.html.erb
<h1>文章列表</h1>
<br />
<% link_to 'New Article', new_admin_article_path %>

<table class="table table-striped span8">
  <tr>    
    <th>标题</th>    
    <th>发布日期</th>        
    <th></th>
    <th></th>    
  </tr>

<% @articles.each do |article| %>
  <tr>    
    <td><%= article.title %></td>
    <td><%= article.published_at.strftime('%Y-%m-%d %H:%M:%S').to_s %></td>
    <td><% article.category_id %></td>
    <td><%= link_to '查看', admin_article_path(article) %>    
    <%= link_to '编辑', edit_admin_article_path(article) %>
    <%= link_to '删除', admin_article_path(article), method: :delete, data: { confirm: '确定删除?' } %></td>
  </tr>
<% end %>
</table>
<div class="span6"><%= will_paginate @articles %></div>
<br />

app/views/admin/articles/new.html.erb
<h1><%= '新建文章' || t('.new_article') %></h1>

<%= render 'form' %>

<% link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="span9 well" style="margin:0px;background-color:white;padding-right:0px;">
	<p>
		<i class="icon-file icon-large" style="color:red"></i>
		<span style="margin-left:10px;color:red;font-weight:bold;font-size:130%"><%= @article.title %></span>
	</p>
	<p style="margin-top:20px">
		<%= @article.body.html_safe %>
	</p>
</div>