config/routes.rb
RailsApp::Application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, :path => "/", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification'}#, :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  get "front/index"
  get "front/admin", :as=>"front_admin"

  resources :categories, only: [:show]

  resources :articles, only: [:show, :index]

  namespace 'admin' do
    resources :articles
    resources :categories
  end  

  root :to=>"front#index", :as=>"front"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :own_id, :display_order, :fixed_menu, :submenu_of
  
  default_scope :order => 'display_order'

  has_many :articles, :dependent => :nullify
  has_many :sub_menus, :dependent => :nullify

  validates_length_of :name, :maximum => 80

  def Category.nav_menu
  	menus = Category.where(:fixed_menu => true)
  end

  def Category.s_menu(item)
  	s_menus = Category.where(:submenu_of => item.id)
  end

  def get_recent_article
    articles.where(:published => true).limit(20)
  end
end

app/controllers/admin/categories_controller.rb
# encoding: utf-8
class Admin::CategoriesController < Admin::BaseController  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.where(:own_id => nil)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if (not @category.own_id.present?) && @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: '成功更新类别名称.' }
        format.json { head :no_content }
      else
        format.html { redirect_to front_admin_url, notice: "无法修改系统类别,只能修改自定义类别" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    if (not @category.own_id.present?)
      @category.destroy
    end

    respond_to do |format|
      format.html { redirect_to front_admin_url, notice: "删除完成" }
      format.json { head :no_content }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :update, :destory]
  # GET /categories
  # GET /categories.json
  # def index
  #   @categories = Category.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @categories }
  #   end
  # end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # # GET /categories/new
  # # GET /categories/new.json
  # def new
  #   @category = Category.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @category }
  #   end
  # end

  # # GET /categories/1/edit
  # def edit
  #   @category = Category.find(params[:id])
  # end

  # # POST /categories
  # # POST /categories.json
  # def create
  #   @category = Category.new(params[:category])

  #   respond_to do |format|
  #     if @category.save
  #       format.html { redirect_to @category, notice: 'Category was successfully created.' }
  #       format.json { render json: @category, status: :created, location: @category }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @category.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PUT /categories/1
  # # PUT /categories/1.json
  # def update
  #   @category = Category.find(params[:id])

  #   respond_to do |format|
  #     if @category.update_attributes(params[:category])
  #       format.html { redirect_to @category, notice: 'Category was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @category.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /categories/1
  # # DELETE /categories/1.json
  # def destroy
  #   @category = Category.find(params[:id])
  #   @category.destroy

  #   respond_to do |format|
  #     format.html { redirect_to categories_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= simple_form_for([:admin, @category], :html => { :class => 'span6 form-horizontal well'}) do |f| %>
  <%= f.input :name, label: '类别名称' %>
  <div class="field" style="margin:10px 0px 10px 0px">
    <label>下拉菜单</label>
    <%= f.collection_select :submenu_of, Category.where(fixed_menu: true), :id, :name %>
  </div>
  <%= f.submit '保存', :class => "btn btn-primary btn-large" %>
  <%= link_to '取消', admin_articles_path, :class => "btn btn-info" %>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>编辑类别</h1>

<%= render 'form' %>

<% link_to 'Show', @category %> |
<% link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>类别列表</h1>

<table>
  <tr>
    <th>类别名</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to '编辑', edit_admin_category_path(category) %></td>
    <td><%= link_to '删除', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '新建分类', new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>新建分类</h1>

<%= render 'form' %>

<% link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<div class="span9 well" style="margin:0px;background-color:white;padding-right:0px;">
	<p id="notice"><%= notice %></p>
	<p>
		<i class="icon-file icon-large" style="color:red"></i>
		<span style="margin-left:10px;color:red;font-weight:bold;font-size:130%"><%= @category.name %></span>
	</p>
	
	<ul style="margin-top:20px;color:red">
		<% @category.articles.each do |article| %>
			<li style="margin-bottom:10px">
				<%= link_to article.title, article, html_options = { :style => 'color:red' } %>
			</li>
		<% end %>	
	</ul>
</div>